// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: wordChecker.proto

package wordCheckerPB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordRequest) Reset() {
	*x = WordRequest{}
	mi := &file_wordChecker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRequest) ProtoMessage() {}

func (x *WordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wordChecker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRequest.ProtoReflect.Descriptor instead.
func (*WordRequest) Descriptor() ([]byte, []int) {
	return file_wordChecker_proto_rawDescGZIP(), []int{0}
}

func (x *WordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordResponse) Reset() {
	*x = WordResponse{}
	mi := &file_wordChecker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordResponse) ProtoMessage() {}

func (x *WordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wordChecker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordResponse.ProtoReflect.Descriptor instead.
func (*WordResponse) Descriptor() ([]byte, []int) {
	return file_wordChecker_proto_rawDescGZIP(), []int{1}
}

func (x *WordResponse) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordResponse) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

var File_wordChecker_proto protoreflect.FileDescriptor

var file_wordChecker_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x50, 0x42, 0x22, 0x21, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x41, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69,
	0x73, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x32, 0x53, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x57, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x72, 0x50, 0x42, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x42,
	0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a,
	0x0e, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x42, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_wordChecker_proto_rawDescOnce sync.Once
	file_wordChecker_proto_rawDescData []byte
)

func file_wordChecker_proto_rawDescGZIP() []byte {
	file_wordChecker_proto_rawDescOnce.Do(func() {
		file_wordChecker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wordChecker_proto_rawDesc), len(file_wordChecker_proto_rawDesc)))
	})
	return file_wordChecker_proto_rawDescData
}

var file_wordChecker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wordChecker_proto_goTypes = []any{
	(*WordRequest)(nil),  // 0: wordCheckerPB.WordRequest
	(*WordResponse)(nil), // 1: wordCheckerPB.WordResponse
}
var file_wordChecker_proto_depIdxs = []int32{
	0, // 0: wordCheckerPB.WordService.CheckWord:input_type -> wordCheckerPB.WordRequest
	1, // 1: wordCheckerPB.WordService.CheckWord:output_type -> wordCheckerPB.WordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wordChecker_proto_init() }
func file_wordChecker_proto_init() {
	if File_wordChecker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wordChecker_proto_rawDesc), len(file_wordChecker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wordChecker_proto_goTypes,
		DependencyIndexes: file_wordChecker_proto_depIdxs,
		MessageInfos:      file_wordChecker_proto_msgTypes,
	}.Build()
	File_wordChecker_proto = out.File
	file_wordChecker_proto_goTypes = nil
	file_wordChecker_proto_depIdxs = nil
}
